[global]
WANDB_MODE = "offline"
WANDB_ENTITY = "gassantos-icuff"
WANDB_PROJECT = "llama32-summarization-poc"
WANDB_RUN_NAME = "llama2-3b-lora-robust-monitoring"
MODEL_NAME = "LLaMA 3.2 3B"
BATCH_SIZE = 2
LEARNING_RATE = 2e-4
EPOCHS = 3
LORA_R = 8
LORA_ALPHA = 16
DATASET = "billsum"
TASK = "summarization"
QUANTIZATION = "4-bit"

[development]
WANDB_MODE = "offline"

[production]
WANDB_MODE = "online"
